### PR TITLE
Added a misc tab to gui

### PR DESCRIPTION
**Pull request by MrGav**
- Demospeed toggle
- Starting/Skipping/Pausing Safezone  
- Time of day buttons

### CODE REVIEW

**Comment by MrGav** [comment]
milnore if you dont acept this yor dayz are mahtced

**Comment by Milxnor** [comment]
i will merge later

**Comment by MrGav** [comment]
Let's fluffing go

**Comment by MrGav** [comment]
Time is up be ready milksnore

**Comment by MrGav** [comment]
why the fluff did this close

**Pull request closed without merging**
